// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlatfortmeDeFormationDeNouveauxRecrus.DataBase;

#nullable disable

namespace PlatfortmeDeFormationDeNouveauxRecrus.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20230308132845_hjkl")]
    partial class hjkl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlatfortmeDeFormationDeNouveauxRecrus.DepartementManagement.Entities.Bureau", b =>
                {
                    b.Property<int>("Bureau_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Bureau_id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BureauName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Bureau_id");

                    b.ToTable("Bureaus");
                });

            modelBuilder.Entity("PlatfortmeDeFormationDeNouveauxRecrus.DepartementManagement.Entities.Categorie", b =>
                {
                    b.Property<int>("Categorie_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Categorie_id"));

                    b.Property<string>("CategorieName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Categorie_id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PlatfortmeDeFormationDeNouveauxRecrus.DepartementManagement.Entities.Departement", b =>
                {
                    b.Property<int>("Departement_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Departement_id"));

                    b.Property<string>("DepartementName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Departement_id");

                    b.ToTable("Departements");
                });

            modelBuilder.Entity("PlatfortmeDeFormationDeNouveauxRecrus.DepartementManagement.Entities.Document", b =>
                {
                    b.Property<int>("Document_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Document_id"));

                    b.Property<int?>("Categorie_id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PieceJointe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Project_id")
                        .HasColumnType("integer");

                    b.HasKey("Document_id");

                    b.HasIndex("Categorie_id");

                    b.HasIndex("Project_id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("PlatfortmeDeFormationDeNouveauxRecrus.DepartementManagement.Entities.Project", b =>
                {
                    b.Property<int>("Project_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Project_id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Project_id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PlatfortmeDeFormationDeNouveauxRecrus.DepartementManagement.Entities.SousDepartement", b =>
                {
                    b.Property<int>("SousDepartement_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SousDepartement_id"));

                    b.Property<int>("Departement_id")
                        .HasColumnType("integer");

                    b.Property<string>("SousDepartementName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SousDepartement_id");

                    b.HasIndex("Departement_id");

                    b.ToTable("SousDepartements");
                });

            modelBuilder.Entity("PlatfortmeDeFormationDeNouveauxRecrus.FormationManagement.Entities.Formation", b =>
                {
                    b.Property<int>("Formation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Formation_id"));

                    b.Property<string>("DateDebut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateFin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Duree")
                        .HasColumnType("integer");

                    b.Property<string>("EnPresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NombreParticipant")
                        .HasColumnType("integer");

                    b.Property<string>("statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Formation_id");

                    b.ToTable("Formations");
                });

            modelBuilder.Entity("PlatfortmeDeFormationDeNouveauxRecrus.FormationManagement.Entities.PlanFormation", b =>
                {
                    b.Property<int>("PlanFormation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanFormation_id"));

                    b.Property<string>("Chapitre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Debut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PlanFormation_id");

                    b.ToTable("PlanFormations");
                });

            modelBuilder.Entity("PlatfortmeDeFormationDeNouveauxRecrus.FormationManagement.Entities.Salle", b =>
                {
                    b.Property<int>("Salle_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Salle_id"));

                    b.Property<string>("BureauName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameSalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Salle_id");

                    b.ToTable("Salles");
                });

            modelBuilder.Entity("PlatfortmeDeFormationDeNouveauxRecrus.ReclamationManagement.Entitie.Reclamation", b =>
                {
                    b.Property<int>("Reclamation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Reclamation_id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("UsersUser_id")
                        .HasColumnType("integer");

                    b.HasKey("Reclamation_id");

                    b.HasIndex("UsersUser_id");

                    b.ToTable("Reclamations");
                });

            modelBuilder.Entity("PlatfortmeDeFormationDeNouveauxRecrus.UserManagement.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Formatteur"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Participant"
                        });
                });

            modelBuilder.Entity("PlatfortmeDeFormationDeNouveauxRecrus.UserManagement.Entities.User", b =>
                {
                    b.Property<int>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("User_id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("User_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("integer");

                    b.Property<int>("UsersUser_id")
                        .HasColumnType("integer");

                    b.HasKey("RolesId", "UsersUser_id");

                    b.HasIndex("UsersUser_id");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("PlatfortmeDeFormationDeNouveauxRecrus.DepartementManagement.Entities.Document", b =>
                {
                    b.HasOne("PlatfortmeDeFormationDeNouveauxRecrus.DepartementManagement.Entities.Categorie", "Categorie")
                        .WithMany("Documents")
                        .HasForeignKey("Categorie_id");

                    b.HasOne("PlatfortmeDeFormationDeNouveauxRecrus.DepartementManagement.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("Project_id");

                    b.Navigation("Categorie");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PlatfortmeDeFormationDeNouveauxRecrus.DepartementManagement.Entities.SousDepartement", b =>
                {
                    b.HasOne("PlatfortmeDeFormationDeNouveauxRecrus.DepartementManagement.Entities.Departement", "Departement")
                        .WithMany("SousDepartements")
                        .HasForeignKey("Departement_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departement");
                });

            modelBuilder.Entity("PlatfortmeDeFormationDeNouveauxRecrus.ReclamationManagement.Entitie.Reclamation", b =>
                {
                    b.HasOne("PlatfortmeDeFormationDeNouveauxRecrus.UserManagement.Entities.User", "Users")
                        .WithMany()
                        .HasForeignKey("UsersUser_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("PlatfortmeDeFormationDeNouveauxRecrus.UserManagement.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlatfortmeDeFormationDeNouveauxRecrus.UserManagement.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUser_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlatfortmeDeFormationDeNouveauxRecrus.DepartementManagement.Entities.Categorie", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("PlatfortmeDeFormationDeNouveauxRecrus.DepartementManagement.Entities.Departement", b =>
                {
                    b.Navigation("SousDepartements");
                });
#pragma warning restore 612, 618
        }
    }
}
